name: Daily GitHub Issue Priority Notifier

on:
  schedule:
    - cron: "30 11 * * *" # 5:00 PM IST
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Debug and verify files
        run: |
          python - <<EOF
          import os
          print("Current working directory:")
          print(os.getcwd())
          print("\nFiles in current directory:")
          for f in os.listdir("."):
              print(" -", f)
          EOF

      - name: Install dependencies
        run: |
          pip install -r ./requirements.txt

      - name: Run issue notifier
        env:
          GITHUB_OWNER: ${{ secrets.G_OWNER }}
          GITHUB_REPO: ${{ secrets.G_REPO }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: |
          python main.py
